---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nzbhydra2
  namespace: media
spec:
  releaseName: nzbhydra2
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: nzbhydra2
      version: 8.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/nzbhydra2
      tag: v3.14.2
    env:
      TZ: "Asia/Riyadh"
    probes:
      startup:
        enabled: true
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
      hosts:
      - host: "nzbhydra.${SECRET_DOMAIN}"
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - "nzbhydra.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /home/abdullah/ssd/k8s/nzbhydra
        mountPath: /config
        accessMode: ReadWriteOnce
      nzbhydra-data:
        enabled: true
        readOnly: false
        type: hostPath
        hostPath: /tank/downloads/nzbhydra
        mountPath: /data/downloads
        accessMode: ReadWriteMany

    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1500Mi
