# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:FvqnJg2n/c3c04M2,iv:1dCulz7RX4YCPB7c1Z96Jtvu67avv3Hp/z/T9O4Ia20=,tag:g+62vVKSwppXWtfOL18AAw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:tF06SB1H2WVOH1L6iKQQNB/UO7eU,iv:ulHHtZzUrsfRQExTtqJ1K3tFKgCUa5CAq0afY74G+OE=,tag:MZ3m08Mqh/2DenLpzDVrIg==,type:str]
    OAUTH_CLIENT_ID: ENC[AES256_GCM,data:v9suUNTO6oRpj8AegxW/N2hAP3LUuGOpQa+BZqnU06a+C8CMnfCMKXpUaCW/1DQY8L8B6SW7Y6Z+qFHxEpvbqKopGe7nD0iB,iv:CJ9N6LIo66CjheGVxXD8IPfmUxkDanWYVInO/32QE1A=,tag:EdWY92raL4JzSpJ4yInW9A==,type:str]
    DEX_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:plMnrUtfEGtMWIkLFDSV4VsFAV1Bth7cmMa39cc7l9WHPsu0Y6Nmyg==,iv:S9a0D/wnhSwH6a0gkwgl1kmWkxvig/CuNbGno+y9jFI=,tag:wZguxQ09hoeGLcKMlRr9oQ==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:ihbHlQT4j2K5hKrvLPOURbNtWjLxNZ3S,iv:1sdrhjZkuVV7cYgHfDTiM3OKU16GAnJVTH2xjFWoFyo=,tag:LkwugRCrGaphOlZwUjl+lA==,type:str]
    DEX_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:i01AHC8ZfDlpY6xh7agpcXXigEg=,iv:PbVLtaJV2bi2teBg9H1RZ8F9aNM0GeX+H4aJQe2SKmA=,tag:fCJJ8qbQiIGIRP2eldKjpw==,type:str]
    OAUTH_COOKIE_SECRET: ENC[AES256_GCM,data:FDc7DuX8krAvToi8h/B1fFIIqmgEi4JTPDMRcsAuJw9rkfIQRxtfoFjwCfb5HbvrDTcweSIE0cFxldUjq90c1+nZhHjd3pCT82EENT68QuizVY2YGx/3uylJz6E=,iv:063Yv3z2K2dXQ1fqpARF3JAHsFR3xuBIxt/h71x/RMo=,tag:w++SdrMEY1v0NpiQyDMv1A==,type:str]
    COOKIE_DOMAIN: ENC[AES256_GCM,data:Z5XrWxhY+S7PI2ll,iv:q8hKanG9rNua6AayDYPr2fGYxSWrRFk/FLkpwfiYKsQ=,tag:P5NNxgyOjJ9tFFN4PDf8Kw==,type:str]
    WHITELIST: ENC[AES256_GCM,data:JaJEw12LJObtXRFDBI86mzwCNPIAh2WnMHBeNrcLjJ+jIy10Of94Ub7sz1/0M+raXX0QcUpfIPvXemb0OdxZ8+JbNYYG8P7LZk0PGpQdTHULcfq749+0D92ZysKO,iv:DONQcz4bJDWYFzMZ+zKRU2ubxkUCX8DAMmur/3HukQg=,tag:ZxeyBJfJDn8hTJfU8YPqZA==,type:str]
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:eT9xTsSvZAoYDe0=,iv:0W8H9VmR2rRhnu54Lx8ML/epjtOIpVItZoPshqeYifc=,tag:SN2PxAfwb9rQp7ollrEUWg==,type:str]
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:ciUihpJUjpri,iv:Y+ZUk6ztYFGIHj8+AXu+ChlIp/VuUriFGeuVo/DzEKA=,tag:RZ30s/gL3j/9KWqRSOCyiQ==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:A/6lSlGE02Y=,iv:ZYHgNA/REUX+UH8rSIwAg5ACAyBhoZQbB4sgbu29YN0=,tag:4P3zHq9DfIEGsE1M5i+beQ==,type:str]
    AUTH_HOST: ENC[AES256_GCM,data:/jLx8cpaCM2QV+m8UEsrdUw=,iv:dVd9fCRXl8WOxUEmetntWKZpO86qDv7VaVnyu2XDshI=,tag:P0ufh5vzAeZOUq1Sil0QDA==,type:str]
    CF_API_KEY: ENC[AES256_GCM,data:qp/xMFFUNn6G3dE3RGvapSYdA0fha1Qy31YJqlGZ6bioWKxvuA==,iv:sXMFLOMZ6QgrtDnJvOg7pDkutkB0bJq6n9flgCrJ8zk=,tag:XLyL6B+G4baPX6YzDWfh7w==,type:str]
    CF_API_EMAIL: ENC[AES256_GCM,data:RCFPKzR3dUF+pAopsjL080nXLsjs,iv:7hM/tjwtJ2a8RDAAItlId3xi0RcFhClVziElZK5j4vQ=,tag:A2SRjIVqaWcvWGYSGRCzMQ==,type:str]
    LOCAL_LAN: ENC[AES256_GCM,data:PhAeliuqohaMDCB/npUl,iv:q1SaJgav1WCx0cAvTzEp4jYB6kJOffNPIwCKPleCeCY=,tag:1UkhEvq0iVVeyAlwA8GKiA==,type:str]
    SECRET_AUTHELIA_JWT_SECRET: ENC[AES256_GCM,data:83Z2LlKBFmn8laGNeGraskjM736P9Os5NLPstMlvBHx6mg==,iv:Z5Eix3/ZOJot6s+kZlbf9XJXkSqu/U0B1p7plAjl/qc=,tag:qcQ2lP3Du7Ss+DVE0D2uMg==,type:str]
    SECRET_AUTHELIA_SESSION_SECRET: ENC[AES256_GCM,data:GQ6qpp5ua64DrAsOy/hxx1hLLg8s9yiTmT/Y2edf1uv4KQ==,iv:ZSNJSbN+nTQ6Y7s+ng4O1GXeFGWY2HYtyRujbgq2rKA=,tag:CYLU/Neejh69Ad6lf8W+iQ==,type:str]
    SECRET_AUTHELIA_POSTGRES_PASSWORD: ENC[AES256_GCM,data:Vr00DdFKff7nuoXDKz+4e0M8TCBg3n4WhmaA5lnbHQdG+A==,iv:xOlmHn7sjNitieZEv1E82ana4+M97dqCUnzsCzvduhE=,tag:LY1CcYWfboEX9AkEuZFxIQ==,type:str]
    SECRET_AUTHELIA_SMTP_EMAIL: ENC[AES256_GCM,data:BpiR1v3w8Ty8l9s51fqZZmZsBMX+,iv:cWkuKxsyVzUDE6vDeu+NdkeXq5RgUJD0DRBhaOVDn8o=,tag:KEMtBhLnCpMYhRGiN9IUAQ==,type:str]
    SECRET_AUTHELIA_SMTP_PASSWORD: ENC[AES256_GCM,data:J8YDxlI7DNDaCNdfDDCf9A==,iv:hnrxtSvGbQYmpP0/oOT96RV7dmDqd1dm2X72G/n4jQ4=,tag:yPtXsv4sEJ+ImWJ7Q1aNMw==,type:str]
    SECRET_POSTGRESQL_KUBE_POSTGRES_PASSWORD: ENC[AES256_GCM,data:C1GUKPdAYk+9qoEPe9Qs66kveoB+ZL4jggq1o3xjD7nSLA==,iv:uhSsh0ALSIGDAOA4BtMJMQ+UjjFZocwV6/BzZs4YxZY=,tag:Ac4UUeL/bIc/cSg4enYzHg==,type:str]
    SECRET_AUTHELIA_USER_ABDULLAH_PASSWORD: ENC[AES256_GCM,data:3W6sjoG8uhE=,iv:eJw28/CQL+aOghxY6ZXKP+HzSTdLnXj0XOkDIXsW1H4=,tag:h9kvZNl8n9/b2rb4QJYLXQ==,type:str]
    SECRET_AUTHELIA_USER_ABDULLAH_EMAIL: ENC[AES256_GCM,data:utPaMPXL6GWPyELsKhVEN+ZQ2PTowrxlUak=,iv:ffNBZ0xIFUiGc8SbmQkh34ZJYACmUrG8zX6GPWUVofE=,tag:pAv9tqiLX931vlwU26KsoA==,type:str]
    SECRET_AUTHELIA_USER_JEJE_PASSWORD: ENC[AES256_GCM,data:hyiNcQSvhCmv,iv:ChRTKR87kl1AiWaAUciF75RAPy8aJH45r+4ZDCoqTqQ=,tag:+nGeLqVIWmxgDquf1PNq+A==,type:str]
    SECRET_AUTHELIA_USER_JEJE_EMAIL: ENC[AES256_GCM,data:T0+pmKHcwT2sjUXz8gcvd3+lakM=,iv:GMMEAAuM96vDXH1+rOcxz6d37iK00B9xpEdUMUb3IOQ=,tag:zbkE9YjrMuBMWvlQ1bK/iA==,type:str]
    SECRET_AUTHELIA_USER_MALIK_PASSWORD: ENC[AES256_GCM,data:dQ4jkyIa+9DG,iv:jWNG5tfT0EY7aNwWrFRUHatrZyOoSvLZAQFv15wboGE=,tag:FfhXCJGsnZmFlr3mX+ayDQ==,type:str]
    SECRET_AUTHELIA_USER_MALIK_EMAIL: ENC[AES256_GCM,data:REB4wMRdoKHUd7tXB2x3EiEIo4GYLes=,iv:l1gypMaOSI9iwRmOB5of5Px7TwpyGY/Kyl24naODwmg=,tag:IKr33NJgD3b5tG+N1PcK+A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-14T15:53:03Z"
    mac: ENC[AES256_GCM,data:mG8iUN40Wdvtin2xstAJ0rFl63gUaEsJGg3L6XfrRfWhqehWdkXb/u1ykcTNTilOOXt9m/aebb7sruDCtlUGbw2rr9V8Zh39vjohpxSlL2T9PJAtJTzUTBDMfGTzBXNjxu8L3TKQcWMoSnPs3pV0kMu8d4ks7TMYgG7nEqgpg58=,iv:9RELwdJEjAavRITLJnJf0Fj2hHGHMO0cSyOGTHWEdkk=,tag:wzpvBUDvpVuwAyZFhhNi9w==,type:str]
    pgp:
        - created_at: "2021-06-14T15:53:03Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxqJrlfNLy7gARAAgC+ArRmIdNQz3IqN5YydKF5U+q8M0olQ3xsUzGw/YTj8
            ilUumghaOLp+KSMJEW6fHBZbL3BBuzyaCsaK2BgBcYqyEWICBsWNgB/1399YvPwj
            2h4fNdG8EInA74maj9tSAbktIyufvld/B1ioWSAfvAwDN8MaFMube1NBG7uHdkZJ
            wUatUvYpIZvA05KPc2SfDpjbjgGj7hgvx/WAiECMh4rmUf7bhM4F3aXsj5tfX+C2
            JYIj0t1fAOnPVtSYp0ovD1Ntuzx404aAFcOp7K7Ea1W1kcc6/2f0IhUHa7CCR0ne
            LejFXjhH1j7IOTYoofeytAmuEpSHSS1r/i2CWvt+VYIz40vo87EzH0pyuWmFhGxv
            LbP0p3WWlX6xw/bSZpepkY/diJX5LvrfkKO81wSgjXfjrJAwO+tsufX08bkaoZyl
            54grLylywju9Lf3awjFM10gRQzLcwgUnQFNhp/mHzXlpOKGg3OehSRKyZa/zlDhf
            ZYtQqYFc+rYyD7soKb7iWINf5Of+hkudZOOHowvCefjJNwHgCsKoszj5Ko2nUiHA
            LGUuAULKoP35T6NN8BATndaYY0lxbBxdaWFA7RwFinhM7xhbZ1ylLFdyYJMR+KLE
            Ajw6LNidJDAfzgVUcEqFzflcOxkPWLq7+wOyuFnxql0q1a+s1hXLkNQYc/UdhL/U
            aAEJAhWzMXYNEor1j+E8Kck1sgBQrVC5uIshkUQKG0T0ot/4j4EdyEFLLiEk6uCd
            J+YwX81RXFzT06zUisprhTFUGRXSuMOJ0MA1wNvZCA8+L50L01PUQug58l0R8w3H
            MFmO3GKGmEh6
            =ywia
            -----END PGP MESSAGE-----
          fp: D027B5C39D3572E0B05085C4EB83E8FDD60FE0A0
        - created_at: "2021-06-14T15:53:03Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAzaFLgIs1yc4ARAAidrLHIEz0ugwuwGcGmBN6rCZw5m8VlxhnWAbVvAMtv9n
            lBf0nxJW4CjUTTv6SG5au9vnz1ev20gt8LmNSfvTk83b5IKINHpyzBp5R5rN2Qvl
            QheyRIZmgQNXtILXUAWeyRUyDLGNJYsAgG5O0+H+RmJul+FU8DM2jleItmFrK1u4
            hqzPkGm+FqOgigC31mIN52OP4a3btQCC7fy0VFWNiro9cnPuI9QVAnovwBr1zKwo
            vDcP734fZzapk8LlHIcDQ2MuCxET9+9Bj+QN7Nc/+ndaf5IXz2L02SvRT1buxHB3
            JdXDKe/Jt4guctPGMGiiIIoh4BwO5a0bqV6r8ejew8nW2YFdaFfVCuVCOBOvmLH3
            RexuQRMxhJ3vB2jwmVgCYCaQ4C5QgukJW+prcRqjLZ2JdvpRE3jN0Kaj/RWl6AVS
            8lLBO8ZFSibVZLAfu0Ydy7+PyT5J+8byU+9j9HyqzOnTmmIncJEp7BjSTQSIzWxA
            XMidmC7vnHmLeUo2g4WpG/3LIF7PZYoHcVQFWeR7AO7D8l2La3VjLiOmakEoKKOQ
            rrAaZEG2/6et1/NZ72AjHe512DmFX6VjQSoJruuiDNkKTPEXA4aeUTqVp67vhIJc
            xXRqbEMvXT2uYjXHwc0tinQ/y5s3C/oyMdBo9/fnSUxFgzBwr+LIFENRPdDH/HDU
            aAEJAhVpfLScxBBovTgcFgNZtTCKPsrenLXyMW2CzqALvQT7exfeynBwuJuu4cih
            SC0dlMkSrcYFo/F5ADaKMViDJywsVr/IMl0M56rQl5UEYLDEB+EyFmAt0pC3c4tk
            SaESo8tgJb+P
            =9tbV
            -----END PGP MESSAGE-----
          fp: 3EBA32A386091A562B0D00D8D0B0D01E85D514F0
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
