---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
#  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: sonarr
      version: 11.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/sonarr
      tag: v3.0.6.1196
    env:
      TZ: "Asia/Riyadh"
      PUID: 1000
      PGID: 1000      
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
      hosts:
      - host: sonarr.${SECRET_DOMAIN}
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - "sonarr.${SECRET_DOMAIN}"
#    podAnnotations:
#      backup.velero.io/backup-volumes: config
    persistence:
      config:
        enabled: true
        storageClass: "local-path"
        size: 5Gi
      media:
        enabled: true
        existingClaim: nfs-media-pvc
        subPath: tv
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 500Mi
#    tolerations:
#    - key: "arm"
#      operator: "Exists"
