apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: media-ingress
  namespace: media
spec:
  rules:
    - host: media.local
      http:
        paths:
        - pathType: Prefix
          path: /sonarr
          backend:
              service: 
                name: sonarr-svc
                port:
                  number: 80
