apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: media-ingress
#  namespace: media
spec:
  rules:
    - host: media.local
      http:
        paths:
          - backend:
              serviceName: sonarr-svc
              servicePort: 80
            path: /sonarr
