# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
stringData:
    cloudflare-token: ENC[AES256_GCM,data:91XkorbXXJEVzwRRygxkJG96FxcxtC60ucuOY78RdXLjjAwBL/WG9w==,iv:qloRvrdlX/p4CnxSStWTA7D0IIQUR1i6xINcJEWOTpk=,tag:PobqJG7AQflxKPESCrhksA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-12T23:59:41Z"
    mac: ENC[AES256_GCM,data:d+A7q5YcG8ao9FPmKWD4DydSldx5LXdRRz5d/1Lx8gRjpWSNxuH1Fwwn9xtEF1Oxp3rd7Tl86aQj5V7W5tD2U1CZPJb7dRaPp6kPRooUQZG7R9yxA121Scrvr4K8+EpLnIR1VKGec0GfzjdxZMaQlay5t+ShEVbkYj9d99H6K9Y=,iv:HHngE6POg05LtsCWHlvSoqsqcKcFAZB4iRYjrP6WLqA=,tag:tJcTMhM4+TOIpogD2FGKIQ==,type:str]
    pgp:
        - created_at: "2021-06-12T23:59:40Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxqJrlfNLy7gAQ/+OlX52KPYswoduOvuybesx6P30thEUsQKbEq/6+l3XgE0
            2JjFevvMIuq/S4yvEnJmmalZzovJ04UzXzduAgg4nCVKgv29k9d2jGx+W7jhhMl5
            Ks8Pxl8oPBnJynMjraviP9niHkVnT5G8Rgjg7AA4J/5yyMynKxhtw1Fwighr+46q
            jrrp7LX/LveMOj7Y8Uhf6bi7CaeSggl56vUFSA+/xUT4fZksRivh/IBr71b8ijQ2
            CuDuVqZ71kjPGwduprwArFr8hPBZZ8uIpdISozFSTnOxDbtmBug3OXNVONL0fX9d
            nTfe5wNnRutlYagj7GAYZfG56yn0BAhyAA90yPcQdIBl2LujnAjtbG9zlWenEyzn
            8Pes9sqoNYivjpfgHLYwjK+2W02A5nw79Eka1g55W1N2/JOFrjAEs4rK98izRjoh
            pVb7nR08VmoPHRI+e5qa6bCnnkO70qkkgy+I+h9l3WfGV69f57pNW5l1wvN2A5bO
            qtoDyPUI5Sd62e3E2iT368zitclZruoHOKm8LZ2zCUmxKbYY+veLM3aWN7Zaife8
            9Cq0j6uVN6ZECjIvrTSB9+UINcDmpU0DcEsnCRyr/2q4+tUxjeiU9Sklb4QW1IFT
            wPVoDisl+P9kVgxkfDPxhjUDokEu+fzRTuk1eoQjrDJlYvFxQBxcIe2WBn0tH23U
            aAEJAhW4JqD63vMZ3jUfHIk5AFT4Ohe59mAPF0+A1p50ao/vFA/r4KA8HhKAoIyJ
            IuBvIiLRTvo7qWtxTGgnUNEVFbPHAhVd0aZu9NtSpTRlxP66lNAIhMJqiYsFyPA6
            bGdH23F63QgB
            =K5ui
            -----END PGP MESSAGE-----
          fp: D027B5C39D3572E0B05085C4EB83E8FDD60FE0A0
        - created_at: "2021-06-12T23:59:40Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAzaFLgIs1yc4AQ/+LUlxKmSpcoPRVLFwHwdy6Ef5/WnI45BejJmVSxpVEwmp
            4rd/xBdvjaOgwzdCSVYsDjj4Wh5yqJeCRy2agRJMrv0faF5J6nfOr4u77lOtw3Vp
            yQWFubGO9W2i5TbetsJkKcIbyf+4+yaN/F4uoCR3dWoDa+ukNFl9iD36A5PKLr9w
            eENqaRUA9Gse+j8ikSONmz2awBoqf15USDi3O/7V10z9mmja1RMJYbmS/kAjlqW8
            +vlhfeNZIpR54HMTn09heYXcPaXhGhdBqo3vuIOuHTtYg4nuheZTcsBXN/xkBuiB
            hVyFjXuiu1RZvcfbIh+j77DsIYi+LjhtBxOk6rvsoq9lkIDm3hJvmb3DVGxtHXq5
            MHJBNOQx5tZBwaqdNzTeMMU/QAERnS4Ih+B5cdO5FOv7Lp40BmYXbYJsEOj6FFf0
            gZKxcaxSqm6/OPmiFMfrS2qMoLPGE51jWiTh1pvyC5v3tfwSkSftPgVkIyUc03fi
            IYY0lZgQ242VU3WngwNiq4SAHzca7AqooRIvmruwz3bnkn6QNOyXzZKYLZi9FErf
            gq5O9WmNuRi94oGnu9vXgcOpiO5ql1UYFpr3NHGBb9ok6FGRG0v/0o3qFtwMSOtd
            J8tJXMfD78a6yNy1WwOAYp/VqeBPgTUusKeqfnI+E3p/Jr+xfk8iJJsBtBCeIq/U
            aAEJAhWk6dwHajSWrV9lIQbwfVmLiGNAFsWCSF6pKi3ByT0h74yhplUNCRWaGqzA
            6XSx+3o+uB3hfewT1EBwzVXEdE0qLlwLC8T7ENhsUeOjYm0ylZVjaswUnudR/SYi
            FXNPy2T1XLse
            =HnBZ
            -----END PGP MESSAGE-----
          fp: 3EBA32A386091A562B0D00D8D0B0D01E85D514F0
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
